spring.application.name=Edu-note
# Configurations pour l'accès à la base de données sous MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/edu_note
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# Configurations JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
